#! /bin/sh

## STARTUP ##

killall pulseaudio&
picom -b &
sxhkd &
nitrogen --set-scaled ~/Pictures/WallPapers/nord/nord.png
setxkbmap -option caps:escape_shifted_capslock &
mpris-proxy &
$HOME/.config/polybar/nord/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr & 
pulseaudio

bspc monitor -d 1 2 3 4 5 6 7 8 


## WINDOW CONFIGUARTION ##


bspc config border_width        2
bspc config window_gap          6 

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true



#### BSPWM COLORING ####

bspc config normal_border_color         "#4C566A"
bspc config active_border_color         "#88C0D0"
bspc config focused_border_color        "#88C0D0"
bspc config presel_feedback_color       "#88C0D0"
bspc config urgent_border_color         "#88C0D0"


## APPLICATION RULES ##


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser-beta desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Spotify state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Gpick state=floating
bspc rule -a Thunar state=floating
bspc rule -a Zathura state=tiled
